### ISSUE TITLE
Pot + Button Arrangement 

### ISSUE THREAD

**Issue by organnoise** [batchku/MO#12]
Pot + Buttons start in the bottom right corner (AN 9, BTN 13). Strange place, it would make more sense if it was in the top left. This can be fixed in code if need be.

![screenshot 2017-09-19 18 36 23](https://user-images.githubusercontent.com/6125506/30618865-596285aa-9d6a-11e7-9ffd-b1b2ea0ef1dd.jpg)

**Comment by batchku** [comment]
fixed in v2-5
